package uz.mediasolutions.referral2.utills.constants;

public interface Message {
    String CHANNEL_POST_SENT = "CHANNEL_POST_SENT";
    String BACK = "BACK";
    String SENT_THIS_LINK = "SENT_THIS_LINK";
    String SHARE_LINK = "SHARE_LINK";
    String SHARING_LINK_MSG = "SHARING_LINK_MSG";
    String LINK_MESSAGE = "LINK_MESSAGE";
    String MENU = "MENU";
    String POST_SENT = "POST_SENT";
    String SAVED = "SAVED";
    String POST = "POST";
    String MENU_MSG = "MENU_MSG";
    String CHALLENGE = "CHALLENGE";
    String INVITE = "INVITE";
    String PRIZE_LIST = "PRIZE_LIST";
    String REACH_TO_ADMIN = "REACH_TO_ADMIN";
    String TELEGRAPH_URL_FOR_CHALLENGE = "TELEGRAPH_URL_FOR_CHALLENGE";
    String TELEGRAPH_LINK_FOR_PRIZE_LIST = "TELEGRAPH_LINK_FOR_PRIZE_LIST";
    String ADMIN_USERNAME = "ADMIN_USERNAME";
    String WHEN_JOINED_MESSAGE = "WHEN_JOINED_MESSAGE";
    String ERROR = "ERROR";
    String REDIRECT_TO_CHANNEL = "REDIRECT_TO_CHANNEL";
    String CHANNEL_URL_REQUEST = "CHANNEL_URL_REQUEST";
    String POST_TYPE = "POST_TYPE";
    String USER_NOT_FOUND_OR_DISABLED = "USER_NOT_FOUND_OR_DISABLED";
    String BAD_REQUEST = "BAD_REQUEST";
    String USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND";
    String MISMATCH_PASSWORDS = "MISMATCH_PASSWORDS";
    String USER_ALREADY_REGISTERED = "USER_ALREADY_REGISTERED";
}
