package uz.mediasolutions.referral2.constants;

public interface Message {
   String WHEN_JOINED_MESSAGE = "WHEN_JOINED_MESSAGE";
   String WHEN_JOINED_MESSAGE2 = "WHEN_JOINED_MESSAGE2";
   String CHALLENGE = "CHALLENGE";
   String INVITE = "INVITE";
   String PRIZE_LIST = "PRIZE_LIST";
   String REACH_TO_ADMIN = "REACH_TO_ADMIN";
   String POST = "POST";
   String BACK = "BACK";
   String YOU_HAVE_NOT_ADMIN_RIGHTS = "YOU_HAVE_NOT_ADMIN_RIGHTS";
   String MENU = "MENU";
   String POST_SENT = "POST_SENT";
   String TELEGRAPH_URL_FOR_CHALLENGE = "TELEGRAPH_URL_FOR_CHALLENGE";
   String TELEGRAPH_LINK_FOR_PRIZE_LIST = "TELEGRAPH_LINK_FOR_PRIZE_LIST";
   String ADMIN_USERNAME = "ADMIN_USERNAME";
   String MENU_MSG = "MENU_MSG";
   String REDIRECT_TO_CHANNEL = "REDIRECT_TO_CHANNEL";
   String CHANNEL_URL_FOREVER = "CHANNEL_URL_FOREVER";
   String LINK_MESSAGE = "LINK_MESSAGE";
   String SAVED = "SAVED";
}
